# Generated by Django 6.0.6 on 2026-06-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. 2022 Mazda CX-5 XD Turbo', max_length=200)),
                ('make', models.CharField(help_text='e.g. Toyota, Mazda, Subaru', max_length=100)),
                ('model', models.CharField(help_text='e.g. CX-5, Land Cruiser', max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('engine_cc', models.PositiveIntegerField(help_text='Engine displacement in cc, e.g. 2500')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=20)),
                ('mileage', models.PositiveIntegerField(help_text='Mileage in km')),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in KES', max_digits=12)),
                ('badge', models.CharField(blank=True, help_text="e.g. 'New Arrival', 'Hot Deal'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('car_interest', models.CharField(blank=True, help_text='e.g. Toyota Prado, budget ~3M', max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, help_text='e.g. Nairobi, Mombasa', max_length=100)),
                ('car_purchased', models.CharField(blank=True, help_text='e.g. 2021 Toyota RAV4', max_length=200)),
                ('quote', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
